apps/administrador/urls.py
from django.conf.urls import url
from apps.administrador import views

urlpatterns = [
    url(r'^perfil/$', views.perfil, name="perfil"),
    url(r'^clientes/$', views.clientes, name="clientes"),
    url(r'^lista_clientes/$', views.listar_clientes, name="lista_clientes"),
    url(r'^empleados/registrar/$', views.registrar_empleado, name="registrar_empleados"),
    url(r'^empleado/contratar/$', views.contratar_empleado, name="contratar_empleado"),
    url(r'^empleados/$', views.empleados, name="empleados"),
    url(r'^lista_empleados/$', views.listar_empleados, name="lista_empleados"),
    url(r'^servicios/registrar/$', views.registrar_servicios, name="registrar_servicios"),
    url(r'^servicios/ofertar/$', views.ofrecer_servicio, name="ofertar_servicios"),
    url(r'^servicios/$', views.servicios, name="servicios"),
]

apps/cliente/urls.py
from django.conf.urls import url
from apps.cliente import views

urlpatterns = [
    url(r'^registro/$', views.registrarCliente, name='registrar'),
    
    url(r'^perfil/$', views.perfil, name="perfil"),
    url(r'^perfil/actualizar/$', views.actualizar_perfil, name="actualizar_perfil"),
]

apps/principal/urls.py
from django.conf.urls import url
from apps.principal import views
from apps.cliente.views import registrar

urlpatterns = [
    url(r'^$', views.inicio, name='inicio'),
    url(r'^ingresar/$', views.ingresar, name='ingresar'),
    url(r'^registrar/$', registrar, name='registrarCliente'),
    
    url(r'^control/tablero/$', views.control, name='tablero'),
    
    url(r'^ingreso/$', views.iniciarSesion, name='ingreso'),
    url(r'^salir/$', views.salir, name="salir"),
    
    url(r'^catalogo/$', views.catalogo, name="catalogo"),
    url(r'^servicios/$', views.listarServicios, name="servicios"),
]

innail/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('apps.principal.urls', namespace="principal")),
    url(r'^cliente/',include('apps.cliente.urls', namespace="cliente")),
    url(r'^administrador/',include('apps.administrador.urls', namespace="administrador")),
    url(r'^empleado/',include('apps.empleado.urls', namespace="empleado")),
    url(r'^reset/password_reset',password_reset,
        {'template_name':'registration/password_reset_form.html','email_template_name':'registration/password_reset_email.html'},
        name="password_reset"),
    url(r'^password_reset_done',password_reset_done,
        {'template_name':'registration/password_reset_done.html'},
        name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-94-Za-z_\-]+)/(?P<token>.+)/$',password_reset_confirm,
    {'template_name':'registration/password_reset_confirm.html'},
    name="password_reset_confirm"),
    url(r'^reset/done',password_reset_complete,
        {'template_name':'registration/password_reset_complete.html'},
        name="password_reset_complete"),
]

templates/control/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es" ng-app="appControl">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}Control{% endblock %} | Panel de control</title>

  <!-- favicon -->
  <link rel="icon" href="{% static 'commons/images/favicon.png' %}">

  <!-- UiKit -->
  <link rel="stylesheet" href="{% static 'commons/css/uikit.min.css' %}">

  <!-- Bootstrap Core CSS -->
  <link href="{% static 'commons/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- DataTables CSS -->
  <link href="{% static 'control/css/datatables/dataTables.bootstrap.min.css' %}" rel="stylesheet">

  <!-- DataTables Responsive CSS -->
  <link href="{% static 'control/css/datatables/dataTables.responsive.css' %}" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="{% static 'control/css/sb-admin.css' %}" rel="stylesheet">

  <!-- Morris Charts CSS -->
  <link href="{% static 'control/css/plugins/morris.css' %}" rel="stylesheet">

  <!-- Custom Fonts -->
  <link href="{% static 'control/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

  <!-- Styles -->
  <link rel="stylesheet" href="{% static 'control/css/style.css' %}">

  {% block extralink %}

  {% endblock %}

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
  <div id="wrapper">
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="{% url 'principal:tablero' %}">Panel de control de Innail</a>
      </div>

      <ul class="nav navbar-right top-nav">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i>  {{ user.usuario.nombre }} <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li>
            {% if request.user.is_superuser %}
              <a href="{% url 'administrador:perfil' %}"><i class="fa fa-fw fa-user"></i> Perfil</a>
            {% else %}
              <a href="{% url 'empleado:perfil' %}"><i class="fa fa-fw fa-user"></i> Perfil</a>
            {% endif %}
            </li>
            <li class="divider"></li>
            <li>
              <a href="{% url 'principal:salir' %}"><i class="fa fa-fw fa-power-off"></i> Salir</a>
            </li>
          </ul>
        </li>
      </ul>

      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav    side-nav">
          <li class="{% block tablero %}{% endblock %}">
            <a href="{% url 'principal:tablero' %}"><i class="fa fa-fw fa-dashboard"></i> Tablero</a>
          </li>

          {% if request.user.is_superuser %}
          <li class="{% block clientes %}{% endblock %}">
            <a href="{% url 'administrador:clientes' %}"><i class="fa fa-fw fa-users"></i> Clientes</a>
          </li>

          <li class="{% block empleados %}{% endblock %}">
            <a href="{% url 'administrador:empleados' %}"><i class="fa fa-fw fa-users"></i> Empleados</a>
          </li>

          <li class="{% block servicios %}{% endblock %}">
            <a href="{% url 'administrador:servicios' %}"><i class="fa fa-fw fa-book"></i> Servicios</a>
          </li>
          {% endif %}

        </ul>
      </div>
    </nav>

    <div id="page-wrapper">
      <div class="container-fluid">

        {% block content %}

        {% endblock %}

      </div>
    </div>

  </div>

  <!-- jQuery -->
  <script src="{% static 'commons/js/jquery.js' %}"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="{% static 'commons/js/bootstrap.min.js' %}"></script>

  <!-- UiKit -->
  <script src="{% static 'commons/js/uikit.min.js' %}"></script>
  <script src="{% static 'commons/js/uikit-icons.min.js' %}"></script>

  <!-- Angular -->
  <script src="{% static 'commons/js/angular.min.js' %}"></script>
  <script src="{% static 'control/js/angular/appControl.js' %}"></script>

  <!-- DataTables JavaScript -->
  <script src="{% static 'control/js/datatables/js/jquery.dataTables.js' %}"></script>
  <script src="{% static 'control/js/datatables-plugins/dataTables.bootstrap.js' %}"></script>
  <script src="{% static 'control/js/datatables-responsive/dataTables.responsive.js' %}"></script>

  {% block extrascript %}

  {% endblock %}

</body>

</html>

templates/control/perfil.html
{% extends "control/base.html" %}

{% load static %}

{% block title %}Perfil{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      Mi perfil
    </h1>
  </div>
</div>

<ol class="breadcrumb">
  <li><a href="{% url 'principal:tablero' %}"><i class="fa fa-fw fa-dashboard"></i> Tablero</a></li>
  <li class="active"><i class="fa fa-fw fa-user"></i> Perfil</li>
</ol>

<div class="row">
  <div class="col-xs-12">
    <form>
      <div class="form-group">
        <label for="nombre">Nombre completo</label>
        <input type="text" class="form-control" id="nombre" value="{{ user.usuario.nombre }}">
      </div>
      <div class="form-group">
        <label for="email">Correo electrónico</label>
        <input type="text" class="form-control" id="email" disabled value="{{ user.email }}">
      </div>
      <div class="form-group">
        <label for="telefono">Teléfono</label>
        <input type="text" class="form-control" id="telefono" value="{{ user.usuario.telefono }}">
      </div>
      {% if not request.user.is_superuser %}
      <div class="form-group">
        <label for="direccion">Dirección de residencia</label>
        <input type="text" class="form-control" id="direccion" value="{{ user.usuario.direccion }}">
      </div>
      {% endif %}
      <div class="form-group text-right">
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#confirmar">Actualizar mis datos</button>
      </div>
    </form>
  </div>
</div>

<div class="modal fade" id="confirmar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Confirmación de actualización de datos</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <button type="button" class="btn btn-primary">Actualizar</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/control/tablero.html
{% extends "control/base.html" %}

{% load static %}

{% block title %}Tablero{% endblock %}

{% block tablero %}
active
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      Tablero <small>Estadísticas y datos importantes</small>
    </h1>
  </div>
</div>

<ol class="breadcrumb">
  <li class="active"><i class="fa fa-fw fa-dashboard"></i> Tablero</li>
</ol>

<div class="row">
  <div class="col-lg-3 col-md-6">
      <div class="panel panel-primary">
          <div class="panel-heading">
              <div class="row">
                  <div class="col-xs-3">
                      <i class="fa fa-comments fa-5x"></i>
                  </div>
                  <div class="col-xs-9 text-right">
                      <div class="huge">26</div>
                      <div>New Comments!</div>
                  </div>
              </div>
          </div>
          <a href="#">
              <div class="panel-footer">
                  <span class="pull-left">View Details</span>
                  <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                  <div class="clearfix"></div>
              </div>
          </a>
      </div>
  </div>
  <div class="col-lg-3 col-md-6">
      <div class="panel panel-green">
          <div class="panel-heading">
              <div class="row">
                  <div class="col-xs-3">
                      <i class="fa fa-tasks fa-5x"></i>
                  </div>
                  <div class="col-xs-9 text-right">
                      <div class="huge">12</div>
                      <div>New Tasks!</div>
                  </div>
              </div>
          </div>
          <a href="#">
              <div class="panel-footer">
                  <span class="pull-left">View Details</span>
                  <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                  <div class="clearfix"></div>
              </div>
          </a>
      </div>
  </div>
  <div class="col-lg-3 col-md-6">
      <div class="panel panel-yellow">
          <div class="panel-heading">
              <div class="row">
                  <div class="col-xs-3">
                      <i class="fa fa-shopping-cart fa-5x"></i>
                  </div>
                  <div class="col-xs-9 text-right">
                      <div class="huge">124</div>
                      <div>New Orders!</div>
                  </div>
              </div>
          </div>
          <a href="#">
              <div class="panel-footer">
                  <span class="pull-left">View Details</span>
                  <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                  <div class="clearfix"></div>
              </div>
          </a>
      </div>
  </div>
  <div class="col-lg-3 col-md-6">
      <div class="panel panel-red">
          <div class="panel-heading">
              <div class="row">
                  <div class="col-xs-3">
                      <i class="fa fa-support fa-5x"></i>
                  </div>
                  <div class="col-xs-9 text-right">
                      <div class="huge">13</div>
                      <div>Support Tickets!</div>
                  </div>
              </div>
          </div>
          <a href="#">
              <div class="panel-footer">
                  <span class="pull-left">View Details</span>
                  <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                  <div class="clearfix"></div>
              </div>
          </a>
      </div>
  </div>
</div>

<div class="row" id="tablero">

</div>

{% endblock %}

{%block extrascript %}

{% endblock %}