apps/administrador/urls.py
from django.conf.urls import url
from apps.administrador import views

urlpatterns = [
    url(r'^perfil/$', views.perfil, name="perfil"),
    url(r'^clientes/$', views.clientes, name="clientes"),
    url(r'^lista_clientes/$', views.listar_clientes, name="lista_clientes"),
    url(r'^empleados/registrar/$', views.registrar_empleado, name="registrar_empleados"),
    url(r'^empleado/contratar/$', views.contratar_empleado, name="contratar_empleado"),
    url(r'^empleados/$', views.empleados, name="empleados"),
    url(r'^lista_empleados/$', views.listar_empleados, name="lista_empleados"),
    url(r'^servicios/registrar/$', views.registrar_servicios, name="registrar_servicios"),
    url(r'^servicios/ofertar/$', views.ofrecer_servicio, name="ofertar_servicios"),
    url(r'^servicios/$', views.servicios, name="servicios"),
]

apps/cliente/urls.py
from django.conf.urls import url
from apps.cliente import views

urlpatterns = [
    url(r'^registro/$', views.registrarCliente, name='registrar'),
    
    url(r'^perfil/$', views.perfil, name="perfil"),
    url(r'^perfil/actualizar/$', views.actualizar_perfil, name="actualizar_perfil"),
]

apps/empleado/urls.py
from django.conf.urls import url
from apps.empleado import views

urlpatterns = [
    url(r'^perfil/$', views.perfil, name="perfil"),
]

apps/principal/urls.py
from django.conf.urls import url
from apps.principal import views
from apps.cliente.views import registrar

urlpatterns = [
    url(r'^$', views.inicio, name='inicio'),
    url(r'^ingresar/$', views.ingresar, name='ingresar'),
    url(r'^registrar/$', registrar, name='registrarCliente'),
    
    url(r'^control/tablero/$', views.control, name='tablero'),
    
    url(r'^ingreso/$', views.iniciarSesion, name='ingreso'),
    url(r'^salir/$', views.salir, name="salir"),
    
    url(r'^catalogo/$', views.catalogo, name="catalogo"),
    url(r'^servicios/$', views.listarServicios, name="servicios"),
]

innail/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('apps.principal.urls', namespace="principal")),
    url(r'^cliente/',include('apps.cliente.urls', namespace="cliente")),
    url(r'^administrador/',include('apps.administrador.urls', namespace="administrador")),
    url(r'^empleado/',include('apps.empleado.urls', namespace="empleado")),
    url(r'^reset/password_reset',password_reset,
        {'template_name':'registration/password_reset_form.html','email_template_name':'registration/password_reset_email.html'},
        name="password_reset"),
    url(r'^password_reset_done',password_reset_done,
        {'template_name':'registration/password_reset_done.html'},
        name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-94-Za-z_\-]+)/(?P<token>.+)/$',password_reset_confirm,
    {'template_name':'registration/password_reset_confirm.html'},
    name="password_reset_confirm"),
    url(r'^reset/done',password_reset_complete,
        {'template_name':'registration/password_reset_complete.html'},
        name="password_reset_complete"),
]

apps/administrador/models.py
from django.db import models

apps/cliente/models.py
from django.db import models

apps/empleado/models.py
from django.db import models

# Create your models here.

apps/administrador/views.py
import json
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from apps.usuario.models import tipoRol
from apps.usuario.models import Usuario
from apps.principal.models import Servicio

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

@login_required(login_url='/ingresar/',redirect_field_name=None)
def perfil(request):
    pag="control/perfil.html"

    if request.user.usuario.rol_id==1:
        return render(request, pag)
    elif request.user.usuario.rol_id==2:
        return HttpResponseRedirect('/empleado/perfil/')
    elif request.user.usuario.rol_id==3:
        return HttpResponseRedirect('/cliente/perfil/')

    return HttpResponseRedirect('/')

@login_required(login_url='/ingresar/',redirect_field_name=None)
def clientes(request):
    pag="administrador/clientes.html"

    if request.user.usuario.rol_id==1:
        return render(request, pag)
    elif request.user.usuario.rol_id==2:
        return HttpResponseRedirect('/')
    elif request.user.usuario.rol_id==3:
        return HttpResponseRedirect('/cliente/perfil/')

    return HttpResponseRedirect('/')

@login_required(login_url='/ingresar/',redirect_field_name=None)
def listar_clientes(request):
    clientes = Usuario.objects.values('nombre','usuario__username','telefono').filter(rol_id=3)
    lista_clientes = list(clientes)

    return HttpResponse(json.dumps(lista_clientes), content_type="application/json")

@login_required(login_url='/ingresar/',redirect_field_name=None)
def registrar_empleado(request):
    pag="administrador/registrar_empleado.html"

    if request.user.usuario.rol_id==1:
        return render(request, pag)
    elif request.user.usuario.rol_id==2:
        return HttpResponseRedirect('/')
    elif request.user.usuario.rol_id==3:
        return HttpResponseRedirect('/cliente/perfil/')

    return HttpResponseRedirect('/empleados/registrar/')

@login_required(login_url='/ingresar/',redirect_field_name=None)
def contratar_empleado(request):
    if request.method=='POST':
        if 'nombre' in request.POST or 'email' in request.POST or 'telefono' in request.POST or 'direccion' in request.POST or 'password' in request.POST:
            nombre=request.POST['nombre']
            email=request.POST['email']
            telefono=request.POST['telefono']
            direccion=request.POST['direccion']
            password=request.POST['password']
            
            if len(nombre)>0 and len(email)>0 and len(telefono)>0 and len(direccion)>0 and len(password)>0:
                if User.objects.filter(username=email, is_active=True).exists():
                    return HttpResponse('Empleado ya existe')
                else:
                    user=User.objects.create_user(email, email, password)
                    user.save()

                    tRol=tipoRol.objects.get(id=2)

                    usermodelo=Usuario(usuario=user, nombre=nombre, telefono=telefono, rol=tRol, direccion=direccion)
                    usermodelo.save()
            
                    return HttpResponse('Registrado')
            else:
                return HttpResponse('Faltan datos')
        else:
            return HttpResponse('Faltan campos')
    
    return HttpResponseRedirect("/empleados/registrar/")

@login_required(login_url='/ingresar/',redirect_field_name=None)
def empleados(request):
    pag="administrador/empleados.html"

    if request.user.usuario.rol_id==1:
        return render(request, pag)
    elif request.user.usuario.rol_id==2:
        return HttpResponseRedirect('/')
    elif request.user.usuario.rol_id==3:
        return HttpResponseRedirect('/cliente/perfil/')

    return HttpResponseRedirect('/')

@login_required(login_url='/ingresar/',redirect_field_name=None)
def listar_empleados(request):
    empleados = Usuario.objects.values('nombre','usuario__username','telefono', 'direccion').filter(rol_id=2)
    lista_empleados = list(empleados)

    return HttpResponse(json.dumps(lista_empleados), content_type="application/json")

@login_required(login_url="/ingresar/",redirect_field_name=None)
def registrar_servicios(request):
    pag="administrador/registrar_servicio.html"

    if request.user.usuario.rol_id==1:
        return render(request, pag)
    elif request.user.usuario.rol_id==3 or request.user.usuario.rol_id==2:
        return HttpResponseRedirect('/catalogo')

    return HttpResponseRedirect('/')

@login_required(login_url='/ingresar/',redirect_field_name=None)
def ofrecer_servicio(request):
    if request.method=='POST':
        if 'nombre' in request.POST or 'descripcion' in request.POST or 'precio' in request.POST:
            nombre=request.POST['nombre']
            descripcion=request.POST['descripcion']
            precio=request.POST['precio']
            
            if len(nombre)>0 and len(descripcion)>0 and len(precio)>0:
                if Servicio.objects.filter(nombre=nombre).exists():
                    return HttpResponse('Servicio ya existe')
                else:
                    servicio=Servicio(nombre=nombre, descripcion=descripcion, precio=precio)
                    servicio.save()
            
                    return HttpResponse('Registrado')
            else:
                return HttpResponse('Faltan datos')
        else:
            return HttpResponse('Faltan campos')
    
    return HttpResponseRedirect("/administrador/servicios/registrar/")

@login_required(login_url='/ingresar/',redirect_field_name=None)
def servicios(request):
    pag="administrador/servicios.html"

    if request.user.usuario.rol_id==1:
        return render(request, pag)
    elif request.user.usuario.rol_id==3 or request.user.usuario.rol_id==2:
        return HttpResponseRedirect('/catalogo')

    return HttpResponseRedirect('/')

apps/cliente/views.py
from django.shortcuts import render
from django.core import  serializers
from django.http import HttpResponse, HttpResponseBadRequest, HttpRequest, HttpResponseRedirect

from apps.usuario.models import Usuario

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required

def registrar(request):
    pag='cliente/registrar.html'
    
    if not request.user.is_authenticated():
        return render(request,pag)
        
    return HttpResponseRedirect('/cliente/perfil/')

def registrarCliente(request):
    if request.method=='POST':
        if 'nombre' in request.POST or 'email' in request.POST or 'telefono' in request.POST or 'password' in request.POST:
            nombre=request.POST['nombre']
            email=request.POST['email']
            telefono=request.POST['telefono']
            password=request.POST['password']
            
            if len(nombre)>0 and len(email)>0 and len(telefono)>0 and len(password)>0:
                if User.objects.filter(username=email).exists():
                    return HttpResponse('Cliente ya existe')
                else:
                    user=User.objects.create_user(email, email, password)
                    user.save()
            
                    usermodelo=Usuario(usuario=user, nombre=nombre, telefono=telefono)
                    usermodelo.save()
            
                    userfinal=authenticate(username=email, password=password)
                    login(request, userfinal)
            
                    return HttpResponse('Registrado')
            else:
                return HttpResponse('Faltan datos')
        else:
            return HttpResponse('Faltan campos')
    
    return HttpResponseRedirect("/registrar/")

@login_required(login_url='/ingresar/',redirect_field_name=None)
def perfil(request):
    pag="cliente/perfil.html"
    
    if request.user.usuario.rol_id==3:
        return render(request, pag)
    elif request.user.usuario.rol_id==2 or request.user.usuario.rol_id==1:
        return HttpResponseRedirect('/control/tablero/')
    
    return HttpResponseRedirect("/")
    
@login_required(login_url='/ingresar/',redirect_field_name=None)
def actualizar_perfil(request):
    if request.method=='POST':
        if 'nombre' in request.POST or 'telefono' in request.POST or 'password' in request.POST:
            nombre=request.POST['nombre']
            email=request.session.email
            telefono=request.POST['telefono']
            
            if len(nombre)>0 and len(telefono)>0:
                user=Usuario.objects.get(usuario__username=email)
                user=Usuario(nombre=nombre, telefono=telefono)
                user.save()
                
                return HttpResponse('Actualizado')
            else:
                return HttpResponse('Faltan datos')
        else:
            return HttpResponse('Faltan campos')

    return HttpResponseRedirect("/cliente/perfil/")

apps/empleado/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from django.contrib.auth.decorators import login_required

@login_required(login_url='/ingresar/',redirect_field_name=None)
def perfil(request):
    pag="control/perfil.html"

    if request.user.usuario.rol_id==1:
        return HttpResponseRedirect('/administrador/perfil/')
    elif request.user.usuario.rol_id==2:
        return render(request, pag)
    elif request.user.usuario.rol_id==3:
        return HttpResponseRedirect('/cliente/perfil/')

templates/administrador/clientes.html
{% extends "../control/base.html" %}

{% load static %}

{% block title %}Clientes registrados{% endblock %}

{% block clientes %}
active
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      Servicios <small>Catálogo de servicios ofertados</small>
    </h1>
  </div>
</div>

<ol class="breadcrumb">
  <li><a href="{% url 'principal:tablero' %}"><i class="fa fa-fw fa-dashboard"></i> Tablero</a></li>
  <li class="active"><i class="fa fa-fw fa-users"></i> Clientes</li>
</ol>

<div class="datatable_list">
  <table width="100%" class="table table-striped table-hover" id="tabla-servicios">
    <thead>
      <tr>
        <th class="col-md-4">Nombre</th>
        <th class="col-md-4">Correo</th>
        <th class="col-md-4">Teléfono</th>
      </tr>
    </thead>
    <tbody></tbody>
  </table>
</div>
{% endblock %}

{% block extrascript %}
<script>
    $(document).ready(function() {
      listar();
    });

    var listar = function() {
      var tabla = $('#tabla-servicios').DataTable({
        "language": {
          "url": "{% static 'control/js/datatables/js/datatable_spanish.json' %}"
        },
        "ajax": {
           "processing": true,
           "url": "/administrador/lista_clientes/",
           "dataSrc": ""
        },
        "columns":[
          {"data": "nombre"},
          {"data": "usuario__username"},
          {"data": "telefono"}
        ]
      });
    }
</script>
{% endblock %}

templates/administrador/empleados.html
{% extends "../control/base.html" %}

{% load static %}

{% block title %}Empleados{% endblock %}

{% block empleados %}
active
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      Empleados <small>Listado de empleados activos</small>
    </h1>
  </div>
</div>

<ol class="breadcrumb">
  <li><a href="{% url 'principal:tablero' %}"><i class="fa fa-fw fa-dashboard"></i> Tablero</a></li>
  <li class="active"><i class="fa fa-fw fa-users"></i> Empleados</li>
</ol>

<div class="row">
  <div class="col-xs-12">
    <a href="{% url 'administrador:registrar_empleados' %}" class="btn btn-primary btn-lg btn-block">Registrar nuevos empleados</a>
  </div>
</div>

<div class="datatable_list">
  <table width="100%" class="table table-striped table-hover" id="tabla-servicios">
    <thead>
      <tr>
        <th class="col-md-3">Nombre</th>
        <th class="col-md-3">Correo</th>
        <th class="col-md-3">Teléfono</th>
        <th class="col-md-3">Dirección</th>
      </tr>
    </thead>
    <tbody></tbody>
  </table>
</div>
{% endblock %}

{% block extrascript %}
<script>
    $(document).ready(function() {
      listar();
    });

    var listar = function() {
      var tabla = $('#tabla-servicios').DataTable({
        "language": {
          "url": "{% static 'control/js/datatables/js/datatable_spanish.json' %}"
        },
        "ajax": {
           "processing": true,
           "url": "/administrador/lista_empleados/",
           "dataSrc": ""
        },
        "columns":[
          {"data": "nombre"},
          {"data": "usuario__username"},
          {"data": "telefono"},
          {"data": "direccion"}
        ]
      });
    }
</script>
{% endblock %}

templates/administrador/registrar_empleado.html
{% extends "../control/base.html" %}

{% load static %}

{% block title %}Registrar empleado{% endblock %}

{% block empleados %}
active
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      Registrar empleados <small>Agrega nuevos empleados</small>
    </h1>
  </div>
</div>

<ol class="breadcrumb">
  <li><a href="{% url 'principal:tablero' %}"><i class="fa fa-fw fa-dashboard"></i> Tablero</a></li>
  <li class="active"><i class="fa fa-fw fa-book"></i> Servicios</li>
</ol>

<div class="row">
  <div class="col-xs-12" ng-controller="conRegistroEmpleado">
    <form>
      <div class="form-group">
        <label for="nombre">Nombre completo</label>
        <input type="text" class="form-control" id="nombre" ng-model="nombre">
      </div>
      <div class="form-group">
        <label for="email">Correo electrónico</label>
        <input type="text" class="form-control" id="email" ng-model="email">
      </div>
      <div class="form-group">
        <label for="telefono">Teléfono</label>
        <input type="text" class="form-control" id="telefono" ng-model="telefono">
      </div>
      <div class="form-group">
        <label for="direccion">Dirección de residencia</label>
        <input type="text" class="form-control" id="direccion" ng-model="direccion">
      </div>
      <div class="form-group">
        <label for="password">Contraseña</label>
        <input type="password" class="form-control" id="password" ng-model="password">
      </div>
      <div class="form-group text-right">
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#confirmar">Registrar nuevo empleado</button>
      </div>

      <div class="modal fade" id="confirmar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Confirmación de registro de servicio</h4>
            </div>
            <div class="modal-body">
              <div class="row">
                <div class="col-xs-12">
                  <strong>Nombre:</strong> {$ nombre $}
                </div>
                <div class="col-xs-12">
                  <strong>Correo electrónico:</strong> {$ email $}
                </div>
                <div class="col-xs-12">
                  <strong>Telefono:</strong> {$ telefono $}
                </div>
                <div class="col-xs-12">
                  <strong>Dirección:</strong> {$ direccion $}
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal" ng-click="limpiar()">Cancelar</button>
              <button type="button" class="btn btn-primary" data-dismiss="modal" ng-click="registrar()">Registrar</button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock %}

{% block extrascript %}
<script type="text/javascript" src="{% static 'control/js/angular/controllers/conRegistroEmpleado.js' %}"></script>
{% endblock %}

templates/administrador/registrar_servicio.html
{% extends "../control/base.html" %}

{% load static %}

{% block title %}Registrar servicio{% endblock %}

{% block servicios %}
active
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      Registrar servicios <small>Agrega nuevos servicios ofertados al catálogo</small>
    </h1>
  </div>
</div>

<ol class="breadcrumb">
  <li><a href="{% url 'principal:tablero' %}"><i class="fa fa-fw fa-dashboard"></i> Tablero</a></li>
  <li class="active"><i class="fa fa-fw fa-book"></i> Servicios</li>
</ol>

<div class="row">
  <div class="col-xs-12" ng-controller="conRegistroServicio">
    <form>
      <div class="form-group">
        <label for="nombre">Nombre del servicio</label>
        <input type="text" class="form-control" id="nombre" ng-model="nombre">
      </div>
      <div class="form-group">
        <label for="descripcion">Descripción del servicio</label>
        <textarea class="form-control descriptions-textarea" rows="3" id="descripcion" ng-model="descripcion"></textarea>
      </div>
      <div class="form-group">
        <label for="precio">Precio del servicio</label>
        <div class="input-group">
          <div class="input-group-addon">$</div>
          <input type="number" class="form-control" id="precio" ng-model="precio">
        </div>
      </div>
      <div class="form-group text-right">
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#confirmar">Ofertar nuevo servicio</button>
      </div>

      <div class="modal fade" id="confirmar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Confirmación de registro de servicio</h4>
            </div>
            <div class="modal-body">
              <div class="row">
                <div class="col-xs-12">
                  <strong>Nombre:</strong> {$ nombre $}
                </div>
                <div class="col-xs-12">
                  <strong>Descripcion:</strong> {$ descripcion $}
                </div>
                <div class="col-xs-12 text-right">
                  <strong>Precio:</strong> $ {$ precio $}
                </div>
              </div>

            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal" ng-click="limpiar()">Cancelar</button>
              <button type="button" class="btn btn-primary" data-dismiss="modal" ng-click="registrar()">Ofrecer</button>
            </div>
          </div>
        </div>
      </div>

    </form>
  </div>
</div>
{% endblock %}

{% block extrascript %}
<script type="text/javascript" src="{% static 'control/js/angular/controllers/conRegistroServicio.js' %}"></script>
{% endblock %}

templates/administrador/servicios.html
{% extends "../control/base.html" %}

{% load static %}

{% block title %}Servicios{% endblock %}

{% block servicios %}
active
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      Servicios <small>Catálogo de servicios ofertados</small>
    </h1>
  </div>
</div>

<ol class="breadcrumb">
  <li><a href="{% url 'principal:tablero' %}"><i class="fa fa-fw fa-dashboard"></i> Tablero</a></li>
  <li class="active"><i class="fa fa-fw fa-book"></i> Servicios</li>
</ol>

<div class="row">
  <div class="col-xs-12">
    <a href="{% url 'administrador:registrar_servicios' %}" class="btn btn-primary btn-lg btn-block">Registrar nuevos servicios</a>
  </div>
</div>

<div class="datatable_list">
  <table width="100%" class="table table-striped table-hover" id="tabla-servicios">
    <thead>
      <tr>
        <th class="col-md-3">Nombre</th>
        <th class="col-md-8">Descripción</th>
        <th class="col-md-1">Precio</th>
      </tr>
    </thead>
    <tbody></tbody>
  </table>
</div>
{% endblock %}

{% block extrascript %}
<script>
    $(document).ready(function() {
      listar();
    });

    var listar = function() {
      var tabla = $('#tabla-servicios').DataTable({
        "language": {
          "url": "{% static 'control/js/datatables/js/datatable_spanish.json' %}"
        },
        "ajax": {
           "processing": true,
           "url": "/servicios/",
           "dataSrc": ""
        },
        "columns":[
          {"data": "fields.nombre"},
          {"data": "fields.descripcion"},
          {"data": "fields.precio"}
        ]
      });
    }
</script>
{% endblock %}