apps/cliente/urls.py
from django.conf.urls import url
from apps.cliente import views

urlpatterns = [
    url(r'^registro/$', views.registrarCliente, name='registrar'),
    
    url(r'^perfil/$', views.perfil, name="perfil"),
    url(r'^perfil/actualizar/$', views.actualizar_perfil, name="actualizar_perfil"),
]

apps/principal/urls.py
from django.conf.urls import url
from apps.principal import views
from apps.cliente.views import registrar

urlpatterns = [
    url(r'^$', views.inicio, name='inicio'),
    url(r'^ingresar/$', views.ingresar, name='ingresar'),
    url(r'^registrar/$', registrar, name='registrarCliente'),
    
    url(r'^control/tablero/$', views.control, name='tablero'),
    
    url(r'^ingreso/$', views.iniciarSesion, name='ingreso'),
    url(r'^salir/$', views.salir, name="salir"),
    
    url(r'^catalogo/$', views.catalogo, name="catalogo"),
    url(r'^servicios/$', views.listarServicios, name="servicios"),
]

innail/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('apps.principal.urls', namespace="principal")),
    url(r'^cliente/',include('apps.cliente.urls', namespace="cliente")),
    url(r'^administrador/',include('apps.administrador.urls', namespace="administrador")),
    url(r'^empleado/',include('apps.empleado.urls', namespace="empleado")),
    url(r'^reset/password_reset',password_reset,
        {'template_name':'registration/password_reset_form.html','email_template_name':'registration/password_reset_email.html'},
        name="password_reset"),
    url(r'^password_reset_done',password_reset_done,
        {'template_name':'registration/password_reset_done.html'},
        name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-94-Za-z_\-]+)/(?P<token>.+)/$',password_reset_confirm,
    {'template_name':'registration/password_reset_confirm.html'},
    name="password_reset_confirm"),
    url(r'^reset/done',password_reset_complete,
        {'template_name':'registration/password_reset_complete.html'},
        name="password_reset_complete"),
]

apps/principal/models.py
from django.db import models

class Servicio(models.Model):
    nombre=models.CharField(max_length=255)
    descripcion=models.TextField()
    ofertado=models.BooleanField(default=True)
    precio=models.IntegerField(default=0)
    
    def __str__(self):
        return(self.nombre)

apps/principal/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core import  serializers

from apps.usuario.models import Usuario
from apps.principal.models import Servicio

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

""" <----------------> Llamado a plantillas </----------------> """

def ingresar(request):
    pag="principal/ingresar.html"
    
    if not request.user.is_authenticated():
        return render(request,pag)
        
    return HttpResponseRedirect('/cliente/perfil/')

def inicio(request):
    pag="principal/inicio.html"
    
    return render(request,pag)

@login_required(login_url='/ingresar/',redirect_field_name=None)
def control(request):
    pag="control/tablero.html"
    
    if request.user.usuario.rol_id==1 or request.user.usuario.rol_id==2:
        return render(request, pag)
    elif request.user.usuario.rol_id==3:
        return HttpResponseRedirect('/cliente/perfil/')
    
    return HttpResponseRedirect('/')

def catalogo(request):
    pag="cliente/catalogo.html"
    
    return render(request,pag)

""" <----------------> Ingreso y salida del sistema </----------------> """

def iniciarSesion(request):
    if request.method=='POST':
        email=request.POST['email']
        password=request.POST['password']

        user=authenticate(username=email, password=password)

        if user is not None:
            login(request, user)

            us = Usuario.objects.get(usuario__username=request.POST['email'])
            return HttpResponse(str(us.rol.tipo))
        else:
            return HttpResponse('Datos incorrectos')

    return HttpResponseRedirect("/ingresar/")

def salir(request):
    logout(request)

    return HttpResponseRedirect("/")

""" <----------------> Ingreso y salida del sistema </----------------> """

def listarServicios(request):
    #SELECT "principal_servicio"."id", "principal_servicio"."nombre", "principal_servicio"."descripcion", "principal_servicio"."ofertado", "principal_servicio"."precio" FROM "principal_servicio" WHERE "principal_servicio"."ofertado" = True
    servicios=Servicio.objects.filter(ofertado=True)
    data=serializers.serialize('json',servicios)

    return HttpResponse(data, content_type="application/json")

templates/principal/base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="es"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang="es"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="es"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="es" ng-app="appPrincipal"> <!--<![endif]-->
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{% block title %}{% endblock %} | Innail</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Servicios de belleza al alcance de tu mano" />
	<meta name="keywords" content="belleza, cuidado, estilo, experiencia" />
	<meta name="author" content="fb.com/Kuatio" />

  <!--
	//////////////////////////////////////////////////////

	INNAIL, Plataforma para atención a la belleza

	DESARROLLADA por E, Nat y Lo para BD basada en OUTLINE Template

	Website: 		http://freehtml5.co/
	Template: https://freehtml5.co/outline-free-html5-bootstrap-template/

	//////////////////////////////////////////////////////
	 -->

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Favicon -->
	<link rel="shortcut icon" href="{% static 'commons/images/favicon.png' %}">

	<!-- Google Webfonts -->
	<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

  <!-- bootstrap -->
  <!--<link rel="stylesheet" href="{% static 'commons/css/bootstrap.min.css' %}">-->
  <!-- uikit -->
  <link rel="stylesheet" href="{% static 'commons/css/uikit.min.css' %}">
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'cliente/css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
  <link rel="stylesheet" href="{% static 'cliente/css/icomoon.css' %}">
	<!-- Simple Line Icons-->
	<link rel="stylesheet" href="{% static 'cliente/css/simple-line-icons.css' %}">
	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{% static 'cliente/css/magnific-popup.css' %}">
	<!-- Owl Carousel -->
	<link rel="stylesheet" href="{% static 'cliente/css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'cliente/css/owl.theme.default.min.css' %}">
	<!-- Theme Style -->
	<link rel="stylesheet" href="{% static 'cliente/css/style.css' %}">
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'cliente/js/respond.min.js' %}"></script>
	<![endif]-->

	</head>
	<body class="{% block scroll %}{% endblock %}">

	<div id="fh5co-offcanvass">
		<ul>
			<li class="active"><a href="{% url 'principal:inicio' %}" data-nav-section="home">Inicio</a></li>

			{% if not user.usuario %}
			<li><a href="{% url 'principal:ingresar' %}">Ingresar</a></li>
      {% else %}
			<li><a href="{% url 'cliente:perfil' %}">Perfil</a></li>
			<li><a href="{% url 'principal:catalogo' %}">Catálogo</a></li>
			<li><a href="{% url 'principal:salir' %}">Salir</a></li>
			{% endif %}

		</ul>
	</div>

	<div id="fh5co-menu" class="navbar">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle" data-toggle="collapse" data-target="#fh5co-navbar" aria-expanded="false" aria-controls="navbar"><span>Menú</span> <i></i></a>
					<a href="{% url 'principal:inicio' %}" class="navbar-brand"><span>Innail</span></a>
				</div>
			</div>
		</div>
	</div>

	<div id="fh5co-page">
		<div id="fh5co-wrap">

				{% block content %}

				{% endblock %}

		</div>

		<footer id="fh5co-footer" style="">
			<div class="fh5co-overlay"></div>
			<div class="fh5co-footer-content">
				<div class="container">
					<div class="row">
						<div class="col-md-3 col-sm-4 col-md-push-3">
							<h3 class="fh5co-lead">About</h3>
							<ul>
								<li><a href="#">Tour</a></li>
								<li><a href="#">Company</a></li>
								<li><a href="#">Jobs</a></li>
								<li><a href="#">Blog</a></li>
								<li><a href="#">New Features</a></li>
								<li><a href="#">Contact Us</a></li>
							</ul>
						</div>
						<div class="col-md-3 col-sm-4 col-md-push-3">
							<h3 class="fh5co-lead">Support</h3>
							<ul>
								<li><a href="#">Help Center</a></li>
								<li><a href="#">Terms of Service</a></li>
								<li><a href="#">Security</a></li>
								<li><a href="#">Privacy Policy</a></li>
								<li><a href="#">Careers</a></li>
								<li><a href="#">More Apps</a></li>
							</ul>
						</div>
						<div class="col-md-3 col-sm-4 col-md-push-3">
							<h3 class="fh5co-lead">More Links</h3>
							<ul>
								<li><a href="#">Feedback</a></li>
								<li><a href="#">Frequently Ask Questions</a></li>
								<li><a href="#">Terms of Service</a></li>
								<li><a href="#">Privacy Policy</a></li>
								<li><a href="#">Careers</a></li>
								<li><a href="#">More Apps</a></li>
							</ul>
						</div>

						<div class="col-md-3 col-sm-12 col-md-pull-9">
							<div class="fh5co-footer-logo"><a href="{% url 'principal:inicio' %}">Innail</a></div>
							<p class="fh5co-copyright"><small>&copy; 2017. Todos los derechos reservados. <br>	Basado en <a href="https://freehtml5.co/outline-free-html5-bootstrap-template/" target="_blank">OUTLINE Theme</a></small></p>
						</div>

					</div>
				</div>
			</div>
		</footer>
	</div>

  <!-- Modernizr JS -->
  <script src="{% static 'cliente/js/modernizr-2.6.2.min.js' %}"></script>
  <!-- jQuery -->
  <script src="{% static 'commons/js/jquery.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'cliente/js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'commons/js/bootstrap.min.js' %}"></script>
  <!-- uikit -->
  <script src="{% static 'commons/js/uikit.min.js' %}"></script>
  <script src="{% static 'commons/js/uikit-icons.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'cliente/js/jquery.waypoints.min.js' %}"></script>
	<!-- Magnific Popup -->
	<script src="{% static 'cliente/js/jquery.magnific-popup.min.js' %}"></script>
	<!-- Owl Carousel -->
	<script src="{% static 'cliente/js/owl.carousel.min.js' %}"></script>
	<!-- toCount -->
	<script src="{% static 'cliente/js/jquery.countTo.js' %}"></script>
	<!-- Main JS -->
	<script src="{% static 'cliente/js/main.js' %}"></script>
	<!-- angular -->
	<script src="{% static 'commons/js/angular.min.js' %}"></script>
	<script src="{% static 'cliente/js/angular/appPrincipal.js' %}"></script>

  {% block extrascript %}

  {% endblock %}

	</body>
</html>

templates/principal/ingresar.html
{% extends 'principal/base.html' %}

{% load static %}

{% block title %}
  Ingresar
{% endblock %}

{% block scroll %}
  scrolled
{% endblock %}

{% block content %}
<div id="fh5co-main" class="spacer">

  <div class="container to-animate intro-animate-1 fadeInUp animated">

    <div class="col-xs-12">
      <h1 class="text-center">Iniciar sesión</h1>
      <div class="divider text-center">
        <i uk-icon="icon: heart"></i>
      </div>
    </div>

    <div class="sub-spacer">

      <div ng-controller="conIngreso">
        <form>

          {% csrf_token %}

          <div class="row">
            <div class="col-md-6 col-md-offset-3 form">
              <label for="email">Correo electrónico</label>
              <input id="email" type="text" required ng-model="email">
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 col-md-offset-3 form">
              <label for="password">Contraseña</label>
              <input id="password" type="password" required ng-model="password">
            </div>
          </div>

          <div class="row">
            <div class="col-md-3 col-md-offset-6 text-right">
              <button type="submit" class="btn btn-primary" ng-click="ingresar(email, password)">Ingresar</button>
            </div>
          </div>

        </form>

        <div class="row">
          <div class="col-md-6 col-md-offset-3 text-center">
            <span>¿Olvidaste tu contraseña? <a href="{% url 'password_reset' %}">¡Recuperala!</a></span>
            <br>
            <span>¿No tienes una cuenta? <a href="{% url 'principal:registrarCliente' %}">¡Registrate!</a></span>
          </div>
        </div>

      </div>

    </div>
  </div>
</div>
{% endblock %}

{% block extrascript %}
<script type="text/javascript">
//<![CDATA[
  function resize(){
      var heights = window.innerHeight;
      document.getElementById("fh5co-main").style.height = heights + "px";
  }
  resize();
  window.onresize = function() {
      resize();
  };
  //]]>
</script>

<script src="{% static 'cliente/js/angular/controllers/conIngreso.js' %}"></script>
{% endblock %}

templates/principal/inicio.html
{% extends 'principal/base.html' %}

{% load static %}

{% block title %}
  Inicio
{% endblock %}

{% block content %}

<header id="fh5co-hero" data-section="home" role="banner" class="start">
  <div class="fh5co-overlay"></div>
  <div class="fh5co-intro">
    <div class="container">
      <div class="row">

        <div class="col-md-6 fh5co-text">
          <h2 class="to-animate intro-animate-1">Tu experiencia de belleza al siguiente nivel</h2>
          <p class="to-animate intro-animate-2">Encárgate de tu tiempo, nosotros nos encargaremos de tu belleza</p>
          {% if not user.usuario %}
            <p class="to-animate intro-animate-3"><a href="{% url 'principal:ingresar' %}" class="btn btn-primary btn-md"><i class="icon-leaf"></i> Ingresa</a></p>
          {% endif %}
        </div>
        <div class="col-md-6 text-right fh5co-intro-img to-animate intro-animate-4">
          <img src="{% static 'cliente/images/woman.png' %}" alt="">
        </div>

      </div>
    </div>
  </div>
</header>
<div id="fh5co-main">
  <br>
  <br>
  <br>
  <br>
  <br>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div>

{% endblock %}

{% block extrascript %}
<script type="text/javascript">
//<![CDATA[
  function resize(){
      var heights = window.innerHeight;
      document.getElementById("fh5co-hero").style.height = heights + "px";
  }
  resize();
  window.onresize = function() {
      resize();
  };
  //]]>
</script>

<script>

var $this = $( '#fh5co-main' );


$this.waypoint(function(direction) {

  if( direction === 'down' ) {
    $('body').addClass('scrolled');
  }
  else if( direction === 'up' ){
    $('body').removeClass('scrolled');
  }

}, { offset: '-1px' } );

</script>
{% endblock %}